// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import TransactionController from "./transaction_controller"
application.register("transaction", TransactionController)

import WalletsController from "./wallets_controller"
application.register("wallets", WalletsController)
